/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controle.ProdutoControl;
import Modelo.ProdutoModel;
import Objetos.Cliente;
import Objetos.Produto;
import Objetos.ProdutosVenda;
import Objetos.Venda;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Beth
 */
public class buscarProduto extends javax.swing.JFrame {

    /**
     * Creates new form buscarProduto
     */
    public buscarProduto() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    
    ProdutoModel pm = new ProdutoModel();
    Cliente cl = new Cliente();
    Venda dadosDavenda = new Venda();
    ArrayList lista;
    
    
    
    public void armazenarDados(Venda venda) {
        dadosDavenda = venda;
    }
    
    
    public void setCliente (Cliente c){
        cl =c;
    }
    
    
    
    
    
    public void arrumaTabela(String prod){
        ProdutoControl acessar = new ProdutoControl();
        lista = acessar.validarNomePesquisa(prod);
        if (lista != null) {
            DefaultTableModel modelo = (DefaultTableModel) tab_produto.getModel();
            while (modelo.getRowCount() != 0) {
                modelo.removeRow(0);
            }
            for (int i = 0; i < lista.size(); i++) {
                Produto p = new Produto();
                p = (Produto) lista.get(i);
                String[] linha = new String[3];
                linha[0] = String.valueOf(p.getCod());
                linha[1] = p.getNome();
                linha[2] = "R$ " + String.valueOf(p.getPreco());
                modelo.addRow(linha);
                tab_produto.setModel(modelo);
            }
        } else {
            System.out.println("\nArrayList retornou nulo");
        }        
        
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_produto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Busca de produtos");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Produtos encontrados :");

        tab_produto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cod", "Produto", "Preço"
            }
        ));
        tab_produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_produtoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_produto);
        if (tab_produto.getColumnModel().getColumnCount() > 0) {
            tab_produto.getColumnModel().getColumn(0).setMinWidth(90);
            tab_produto.getColumnModel().getColumn(0).setMaxWidth(90);
            tab_produto.getColumnModel().getColumn(2).setMinWidth(95);
            tab_produto.getColumnModel().getColumn(2).setMaxWidth(95);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab_produtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_produtoMouseClicked
        // TODO add your handling code here:
        int posicao = tab_produto.getSelectedRow();
        Produto prod = (Produto) lista.get(posicao);
        ProdutosVenda prodVenda = new ProdutosVenda();
        prodVenda.setCodProduto(prod.getCod());
        prodVenda.setCodVenda(dadosDavenda.getCodVenda());
        prodVenda.setNomeProduto(prod.getNome());
        prodVenda.setQtdProduto(1);
        prodVenda.setPreco(prod.getPreco());
        prodVenda.setTotalProduto(TOP_ALIGNMENT);
        dadosDavenda.addItem(prodVenda);
        System.out.println("\nQtd da Lista em buscar produto " + dadosDavenda.retornarItens().size());
        cadastrarVenda cv = new cadastrarVenda();
        cv.cl = cl;
        cv.arrumaTela(dadosDavenda);
        if(dadosDavenda.getCodVenda()!=0)
        cv.organizarUpdate();
        // fechar = true;
        cv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tab_produtoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buscarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buscarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buscarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buscarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buscarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab_produto;
    // End of variables declaration//GEN-END:variables
}
