
package View;

import Objetos.Produto;
import Modelo.ProdutoModel;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;



public class visualizarProdutos extends javax.swing.JFrame {

    
    
      ProdutoModel produtoModel = new ProdutoModel();
    
    
    /**
     * Creates new form visualizarProdutos
     */
    public visualizarProdutos() {
        initComponents();
       // this.setLocationRelativeTo(null);
       //this.setExtendedState(MAXIMIZED_BOTH);
        arrumarTela();
    }
    
    
        public void arrumarTela() {
        ct_nomeProd.setText("");
        ct_nomeProd.requestFocus();
        arrumaTabela();
    }

    
    
                public void arrumaTabela() {
                    
                    
        ArrayList resultado = produtoModel.pesquisar(ct_nomeProd.getText());
        if (resultado != null) {
            DefaultTableModel modelo = (DefaultTableModel) tabela_produto.getModel();
            while (modelo.getRowCount() != 0) {
                modelo.removeRow(0);
            }
            for (int i = 0; i < resultado.size(); i++) {
                Produto prod = new Produto();
                prod = (Produto) resultado.get(i);
                String[] linha = new String[3];
                linha[0] = String.valueOf(prod.getCod());
                linha[1] = prod.getNome();
                linha[2] = String.valueOf(prod.getPreco());
                modelo.addRow(linha);
                tabela_produto.setModel(modelo);
            }
        } else {
            System.out.println("\nArrayList retornou nulo");
        }
    }
    
    
    
  
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ct_nomeProd = new javax.swing.JTextField();
        bt_pesquisarProd = new javax.swing.JButton();
        bt_novoProd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_produto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Produtos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Nome:");

        bt_pesquisarProd.setText("Pesquisar");
        bt_pesquisarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarProdActionPerformed(evt);
            }
        });

        bt_novoProd.setText("Novo");
        bt_novoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_novoProdActionPerformed(evt);
            }
        });

        tabela_produto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cod", "Nome", "Valor Unidade"
            }
        ));
        tabela_produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_produtoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela_produto);
        if (tabela_produto.getColumnModel().getColumnCount() > 0) {
            tabela_produto.getColumnModel().getColumn(0).setMinWidth(95);
            tabela_produto.getColumnModel().getColumn(0).setMaxWidth(95);
            tabela_produto.getColumnModel().getColumn(2).setMinWidth(95);
            tabela_produto.getColumnModel().getColumn(2).setMaxWidth(95);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ct_nomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(bt_pesquisarProd)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_novoProd))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ct_nomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_pesquisarProd)
                    .addComponent(bt_novoProd))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_pesquisarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarProdActionPerformed
        // TODO add your handling code here:
        arrumaTabela();
        ct_nomeProd.setText("");
        ct_nomeProd.requestFocus();
    }//GEN-LAST:event_bt_pesquisarProdActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
                Inicial ini = new Inicial();
        ini.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void bt_novoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_novoProdActionPerformed
        // TODO add your handling code here:
        cadastroProduto p = new cadastroProduto();
        this.setVisible(false);
        p.arrumaInsert();
        p.setVisible(true);
    }//GEN-LAST:event_bt_novoProdActionPerformed

    private void tabela_produtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_produtoMouseClicked
        // TODO add your handling code here:
        int clicado = tabela_produto.getSelectedRow();
        Produto prod = new Produto();
        prod.setCod(Integer.parseInt(tabela_produto.getValueAt(clicado,0).toString()));
        prod.setNome(tabela_produto.getValueAt(clicado,1).toString());
        prod.setPreco(Float.parseFloat(tabela_produto.getValueAt(clicado,2).toString()));
        this.setVisible(false);
        cadastroProduto cadPro = new cadastroProduto();
        cadPro.arrumaUpdate(prod);
        cadPro.setVisible(true);
        ct_nomeProd.setText("");
    }//GEN-LAST:event_tabela_produtoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visualizarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visualizarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visualizarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visualizarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new visualizarProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_novoProd;
    private javax.swing.JButton bt_pesquisarProd;
    private javax.swing.JTextField ct_nomeProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabela_produto;
    // End of variables declaration//GEN-END:variables
}
