/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Banco.Banco;
import Modelo.ProdutosVendaModel;
import Modelo.VendaModel;
import Objetos.Venda;
import Objetos.ProdutosVenda;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Beth
 */
public class visualizarVendas extends javax.swing.JFrame {
    
    
    ArrayList listaVendas = new ArrayList();
    Venda vend = new Venda();
    VendaModel vendModel = new VendaModel();
    ProdutosVendaModel produtosVenda = new ProdutosVendaModel();
    Banco banco = new Banco();
    
    

    /**
     * Creates new form visualizarVendas
     */
    public visualizarVendas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    
    
    public void arrumatela(){
       

      arrumarTabela();  
    }
    
    
    
    
    public void arrumarTabela() {
      
            String sql = "select * from listaven;";
        ArrayList resultado =  vendModel.pesquisar2(sql);
            if (resultado != null) {
            DefaultTableModel modelo = (DefaultTableModel) Tab_vendas.getModel();
            //System.out.println(modelo.getRowCount());
            //System.out.println(resultado.size());
            while (modelo.getRowCount() != 0) {
                modelo.removeRow(0);
                            System.out.println(modelo.getRowCount());

            } 
            for (int i = 0; i < resultado.size(); i++) {
                Venda venda = new Venda();
                venda = (Venda) resultado.get(i);
                String[] linha = new String[4];
                linha[0] = String.valueOf(venda.getCodVenda());
                linha[1] = String.valueOf(venda.getNome());
                linha[2] = String.valueOf(venda.getEndereco());
                linha[3] = String.valueOf(venda.getTot_venda());
                modelo.addRow(linha);
                Tab_vendas.setModel(modelo);
            }
        } else {
            System.out.println("\nArrayList retornou nulo");
        }     
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ct_nomeCliente = new javax.swing.JTextField();
        bt_pesquisar = new javax.swing.JButton();
        bt_novaVenda = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tab_vendas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de vendas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Nome:");

        bt_pesquisar.setText("Pesquisar");

        bt_novaVenda.setText("Nova Venda");
        bt_novaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_novaVendaActionPerformed(evt);
            }
        });

        Tab_vendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Cliente", "Endereço", "Total"
            }
        ));
        Tab_vendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tab_vendasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tab_vendas);
        if (Tab_vendas.getColumnModel().getColumnCount() > 0) {
            Tab_vendas.getColumnModel().getColumn(0).setMinWidth(50);
            Tab_vendas.getColumnModel().getColumn(0).setMaxWidth(50);
            Tab_vendas.getColumnModel().getColumn(3).setMinWidth(65);
            Tab_vendas.getColumnModel().getColumn(3).setMaxWidth(65);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ct_nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_pesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(bt_novaVenda))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ct_nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_pesquisar)
                    .addComponent(bt_novaVenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_novaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_novaVendaActionPerformed
        // TODO add your handling code here:
        buscarCliente bc = new buscarCliente();
        bc.arrumaTab();
        bc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_novaVendaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        Inicial i = new Inicial();
        i.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void Tab_vendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tab_vendasMouseClicked
        // TODO add your handling code here:
        int codCliente = 0;
        cadastrarVenda cadVenda = new cadastrarVenda();
        int linha = Tab_vendas.getSelectedRow();
        Venda venda = new Venda();
        
        venda.setCodVenda(Integer.parseInt(Tab_vendas.getValueAt(linha, 0).toString()));
        venda.setNome(Tab_vendas.getValueAt(linha, 1).toString());
        try {
            codCliente = vendModel.retornaCliente(venda.getCodVenda());
        } catch (SQLException ex) {
            Logger.getLogger(visualizarVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
        venda.setCodCliente(codCliente);
        venda.setTot_venda(Float.parseFloat(Tab_vendas.getValueAt(linha, 3).toString()));
        
        this.setVisible(false);
        cadVenda.arrumaTelaTeste(venda);
        cadVenda.setVisible(true);

    }//GEN-LAST:event_Tab_vendasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visualizarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visualizarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visualizarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visualizarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new visualizarVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tab_vendas;
    private javax.swing.JButton bt_novaVenda;
    private javax.swing.JButton bt_pesquisar;
    private javax.swing.JTextField ct_nomeCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
